apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aap-qa
resources:
- aap-qa-namespace.yml
- aap-qa-operatorgroup.yml
- aap-qa-subscription.yml
- aap-qa-ansibleautomationplatform.yml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true

