apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: aap-dev
resources:
- aap-dev-namespace.yml
- aap-dev-operatorgroup.yml
- aap-dev-subscription.yml
- aap-dev-ansibleautomationplatform.yml
commonAnnotations:
  argocd.argoproj.io/sync-options: SkipDryRunOnMissingResource=true
